#!/usr/bin/env python -B
# Copyright: (c) 2018, Gonzalo Alvarez
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

import os
import logging

from ephemeral import (CommandLineManager, EphemeralStoreManager, ContextManager, configure_logging)

def main():
    epherstore = EphemeralStoreManager()
    configure_logging(epherstore.get_store_path())
    logging.info('Starting up Ephemeral')
    context = ContextManager(epherstore)

    climanager = CommandLineManager()
    cli = context.session.cli = climanager.get_args()
    if cli.command:
        cli.command(context)

if __name__ == "__main__":
    main()
