#!/usr/bin/env python
import sys
import os
import json
import site

from pylib.cli import CommandLineManager
from pylib.epher import EphemeralStoreManager 
from pylib.epher import ContextManager

def main():
    epherstore = EphemeralStoreManager()
    context = ContextManager(epherstore)

    climanager = CommandLineManager()
    cli = context.session.cli = climanager.get_args()
    context.session.verbose = True
    if cli.command:
        cli.command(context)

if __name__ == "__main__":
    main()
