#!/usr/bin/env python
import os
import logging

from pylib.epher import CommandLineManager
from pylib.epher import EphemeralStoreManager 
from pylib.epher import ContextManager
from pylib.epher import configure_logging

LOGGING_FILE = 'epher.log'

def main():
    epherstore = EphemeralStoreManager()
    configure_logging(os.path.join(epherstore.get_store_path(), LOGGING_FILE))
    logging.info('Starting up Ephemeral')
    context = ContextManager(epherstore)

    climanager = CommandLineManager()
    cli = context.session.cli = climanager.get_args()
    if cli.command:
        cli.command(context)

if __name__ == "__main__":
    main()
